# for bird-api-service and bird-image-service

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bird-api-service
  labels:
    app: {{ .Release.Name }}-bird-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4201
      nodePort: {{ .Values.birdApi.nodePort }}
  selector:
    app: {{ .Release.Name }}-bird-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bird-image-api-service
  labels:
    app: {{ .Release.Name }}-bird-image-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4200
      nodePort: {{ .Values.birdImageApi.nodePort }}
  selector:
    app: {{ .Release.Name }}-bird-image-api
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bird-chart.fullname" . }}
  labels:
    {{- include "bird-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bird-chart.selectorLabels" . | nindent 4 }}
