apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bird-api
  template:
    metadata:
      labels:
        app: bird-api
    spec:
      containers:
      - name: bird-api
        image: bruno74t/bird-api
        ports:
        - containerPort: 4201
---
apiVersion: v1
kind: Service
metadata:
  name: bird-api-service
spec:
  selector:
    app: bird-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4201
  type: NodePort
