name: CI/CD for Bird APIs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_HOST: tcp://localhost:2375

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log into Docker Hub
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_SYMBOLS_ALLOWED }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Build and push bird API image
      - name: Build and Push Bird API Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bird-api:v.1.0.2 ./bird
          docker push ${{ secrets.DOCKER_USERNAME }}/bird-api:v.1.0.2

      # Step 5: Build and push birdImage API image
      - name: Build and Push BirdImage API Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bird-image-api:v.1.0.2 ./birdImage
          docker push ${{ secrets.DOCKER_USERNAME }}/bird-image-api:v.1.0.2
